/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminCategoriesRouteImport } from './routes/_admin.categories'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminGalleryRouteImport } from './routes/_admin.gallery'
import { Route as AdminHomepageRouteImport } from './routes/_admin.homepage'
import { Route as AdminMobileRouteImport } from './routes/_admin.mobile'
import { Route as AdminNotificationsRouteImport } from './routes/_admin.notifications'
import { Route as AdminPaymentsRouteImport } from './routes/_admin.payments'
import { Route as AdminPlansRouteImport } from './routes/_admin.plans'
import { Route as AdminReportsRouteImport } from './routes/_admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminSponsorsRouteImport } from './routes/_admin.sponsors'
import { Route as AdminUsersRouteImport } from './routes/_admin.users'
import { Route as AdminSponsorsIndexRouteImport } from './routes/_admin.sponsors.index'
import { Route as AdminSponsorsIdRouteImport } from './routes/_admin.sponsors.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMobileRoute = AdminMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorsIndexRoute = AdminSponsorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSponsorsRoute,
} as any)
const AdminSponsorsIdRoute = AdminSponsorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSponsorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AdminCategoriesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/gallery': typeof AdminGalleryRoute
  '/homepage': typeof AdminHomepageRoute
  '/mobile': typeof AdminMobileRoute
  '/notifications': typeof AdminNotificationsRoute
  '/payments': typeof AdminPaymentsRoute
  '/plans': typeof AdminPlansRoute
  '/reports': typeof AdminReportsRoute
  '/settings': typeof AdminSettingsRoute
  '/sponsors': typeof AdminSponsorsRouteWithChildren
  '/users': typeof AdminUsersRoute
  '/sponsors/$id': typeof AdminSponsorsIdRoute
  '/sponsors/': typeof AdminSponsorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AdminCategoriesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/gallery': typeof AdminGalleryRoute
  '/homepage': typeof AdminHomepageRoute
  '/mobile': typeof AdminMobileRoute
  '/notifications': typeof AdminNotificationsRoute
  '/payments': typeof AdminPaymentsRoute
  '/plans': typeof AdminPlansRoute
  '/reports': typeof AdminReportsRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/sponsors/$id': typeof AdminSponsorsIdRoute
  '/sponsors': typeof AdminSponsorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/categories': typeof AdminCategoriesRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/gallery': typeof AdminGalleryRoute
  '/_admin/homepage': typeof AdminHomepageRoute
  '/_admin/mobile': typeof AdminMobileRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/payments': typeof AdminPaymentsRoute
  '/_admin/plans': typeof AdminPlansRoute
  '/_admin/reports': typeof AdminReportsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/sponsors': typeof AdminSponsorsRouteWithChildren
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/sponsors/$id': typeof AdminSponsorsIdRoute
  '/_admin/sponsors/': typeof AdminSponsorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories'
    | '/dashboard'
    | '/gallery'
    | '/homepage'
    | '/mobile'
    | '/notifications'
    | '/payments'
    | '/plans'
    | '/reports'
    | '/settings'
    | '/sponsors'
    | '/users'
    | '/sponsors/$id'
    | '/sponsors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categories'
    | '/dashboard'
    | '/gallery'
    | '/homepage'
    | '/mobile'
    | '/notifications'
    | '/payments'
    | '/plans'
    | '/reports'
    | '/settings'
    | '/users'
    | '/sponsors/$id'
    | '/sponsors'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/categories'
    | '/_admin/dashboard'
    | '/_admin/gallery'
    | '/_admin/homepage'
    | '/_admin/mobile'
    | '/_admin/notifications'
    | '/_admin/payments'
    | '/_admin/plans'
    | '/_admin/reports'
    | '/_admin/settings'
    | '/_admin/sponsors'
    | '/_admin/users'
    | '/_admin/sponsors/$id'
    | '/_admin/sponsors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/categories': {
      id: '/_admin/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/gallery': {
      id: '/_admin/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/homepage': {
      id: '/_admin/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/mobile': {
      id: '/_admin/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof AdminMobileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/payments': {
      id: '/_admin/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/plans': {
      id: '/_admin/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reports': {
      id: '/_admin/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sponsors': {
      id: '/_admin/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sponsors/': {
      id: '/_admin/sponsors/'
      path: '/'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof AdminSponsorsIndexRouteImport
      parentRoute: typeof AdminSponsorsRoute
    }
    '/_admin/sponsors/$id': {
      id: '/_admin/sponsors/$id'
      path: '/$id'
      fullPath: '/sponsors/$id'
      preLoaderRoute: typeof AdminSponsorsIdRouteImport
      parentRoute: typeof AdminSponsorsRoute
    }
  }
}

interface AdminSponsorsRouteChildren {
  AdminSponsorsIdRoute: typeof AdminSponsorsIdRoute
  AdminSponsorsIndexRoute: typeof AdminSponsorsIndexRoute
}

const AdminSponsorsRouteChildren: AdminSponsorsRouteChildren = {
  AdminSponsorsIdRoute: AdminSponsorsIdRoute,
  AdminSponsorsIndexRoute: AdminSponsorsIndexRoute,
}

const AdminSponsorsRouteWithChildren = AdminSponsorsRoute._addFileChildren(
  AdminSponsorsRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminMobileRoute: typeof AdminMobileRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSponsorsRoute: typeof AdminSponsorsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminMobileRoute: AdminMobileRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSponsorsRoute: AdminSponsorsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
